Created cards component and courses component
saeedmabrouk21/Udemy-website-React-Framework pull request #1
Opened 2022-08-22 10:12 UTC by saeedmabrouk21

2022-08-25 12:26 UTC, ahmed2m requested changes
Great work, small comments

2022-08-25 12:26 UTC, ahmed2m commented on src/excel_res.json
> +{
Any reason this file isn't in `data` folder?

2022-08-25 12:26 UTC, ahmed2m commented on src/components/Card.js
> +function Card(obj) {
Nitpick (no need to change it, just a tip): Given that you only use/need the `json` value from `obj`, you could've sent either the json property from the Courses component OR distructed the props like this
```js
function card({ json }) {
```

2022-08-25 12:26 UTC, ahmed2m commented on src/components/Card.js
> +    </>
I now understand what you meant, yeah this works but kind of obviously repetitive code.
With the help of ES6 you can create a new array of size n and loop on it immediately!
(NOTE: need to change FullStar and NoStar to components (Function & first letter is capital) to add key prop because of the loop)
PS: the second argument of map is the index.

```js
  const FullStar = () => (
    <span className={[styles.checked, "fa fa-star"].join(" ")}></span>
  );
  const halfStar = (
    <span className={[styles.checked, "fa fa-star-half-full"].join(" ")}></span>
  );
  const NoStar = () => (
    <span className={[styles.checked, "fa fa-star-o"].join(" ")}></span>
  );
...
...
  {[...Array(whole)].map((_, ix) => <FullStar key={ix} />)}
  {remainder > 0 && remainder < 0.3? <NoStar /> : remainder < 0.8 ? halfStar : <FullStar />} 
  {[...Array(emptyStars)].map((_, ix) => <NoStar key={ix} />)}
```

2022-08-25 12:31 UTC, saeedmabrouk21 commented on src/excel_res.json
> +{
Sorry .I think it happened cuz I use VS explorer to copy files

2022-08-29 11:23 UTC, ahmed2m approved these changes

2022-08-29 11:25 UTC, merged